# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ed1a6bccc18d28227371d3b01b9befbcde960c3a63b2bf485f113a83bb0088a33c580688d211bf5f0dbafbe3d2a79791ebef9ded8311d54e41e389c68fb674c

test:
  secret_key_base: cf86baa1aa0a3f66bec9a437505e86e2702c70cbc0412d98e9b1e9c1f0fa734eb32123ddcee6e43d1d75fa06759e88f34ed6a53042eff7e5207b06b9a8ae45f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
